# Generated by Django 6.0 on 2026-01-09 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('COMMANDER', 'Base Commander'), ('LOGISTICS', 'Logistics Officer')], default='LOGISTICS', max_length=20),
        ),
    ]
