# Generated by Django 6.0 on 2026-01-09 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0002_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('COMMANDER', 'Base Commander'), ('LOGISTICS', 'Logistics Officer')], default='COMMANDER', max_length=20),
        ),
    ]
